// FD/react-todo-app/src/components/CompletedTodos.tsx
import { useState, useEffect } from "react";
import { useParams, Link as RouterLink } from "react-router-dom";
import * as api from "../apiService";
import type { Todo, TodoList } from "../types";

function CompletedTodos() {
  const { listId } = useParams<{ listId: string }>();
  const [completedTodos, setCompletedTodos] = useState<Todo[]>([]);
  const [currentList, setCurrentList] = useState<TodoList | null>(null);
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!listId) return;

    const fetchCompleted = async () => {
      try {
        setLoading(true);
        setError(null);
        const listDetails = await api.getTodoListById(listId);
        setCurrentList(listDetails);

        const allTodos = await api.getTodosForList(listId);
        setCompletedTodos(allTodos.filter((todo) => todo.done));
      } catch (err) {
        console.error("Failed to load completed todos", err);
        setError("Failed to load completed items.");
      } finally {
        setLoading(false);
      }
    };
    fetchCompleted();
  }, [listId]);

  const handleMarkAsNotDone = async (todo: Todo) => {
    if (!listId || !todo._id) return;
    try {
      await api.updateTodoInList(listId, todo._id, { done: false });
      setCompletedTodos((prevTodos) =>
        prevTodos.filter((t) => t._id !== todo._id)
      );
    } catch (err) {
      console.error("Failed to mark as not done", err);
      setError("Failed to update item. Please try again.");
    }
  };

  const handleDeleteCompletedTodo = async (todoId: string) => {
    if (!listId) return;
    if (
      window.confirm(
        "Are you sure you want to permanently delete this completed task?"
      )
    ) {
      try {
        // Backend returns ALL todos after delete, so we re-filter for completed ones
        const allTodosAfterDelete = await api.deleteTodoFromList(
          listId,
          todoId
        );
        setCompletedTodos(allTodosAfterDelete.filter((todo) => todo.done));
      } catch (err) {
        console.error("Failed to delete completed todo", err);
        setError("Failed to delete item. Please try again.");
      }
    }
  };

  if (loading)
    return (
      <div className="container mt-4">
        <p>Loading completed items...</p>
      </div>
    );
  if (error)
    return (
      <div className="container mt-4">
        <p style={{ color: "red" }}>Error: {error}</p>
      </div>
    );
  if (!currentList)
    return (
      <div className="container mt-4">
        <p>List not found.</p>
      </div>
    );

  return (
    <div className="container mt-4">
      <div className="mb-3">
        <RouterLink
          to={`/lists/${listId}`}
          className="btn btn-sm btn-outline-secondary"
        >
          « Back to Active Tasks
        </RouterLink>
      </div>

      <div className="py-3 px-4 mb-4 bg-light rounded-3 text-center">
        <h1>
          {currentList.name} - Completed Tasks
          <span className="badge bg-success text-white ms-2">
            {completedTodos.length}
          </span>
        </h1>
      </div>

      <div className="row justify-content-center">
        <div className="col-sm-8 col-md-6">
          <ul className="list-group">
            {completedTodos.length === 0 && (
              <li className="list-group-item text-center">
                No tasks completed yet.
              </li>
            )}
            {completedTodos.map((todo) => (
              <li
                key={todo._id}
                className="list-group-item d-flex justify-content-between align-items-center"
              >
                <span className="text-decoration-line-through text-muted">
                  {todo.text}
                </span>
                <div>
                  <button
                    onClick={() => handleMarkAsNotDone(todo)}
                    className="btn btn-sm btn-outline-warning me-2"
                    title="Mark as not done"
                  >
                    Undo
                  </button>
                  <button
                    onClick={() => handleDeleteCompletedTodo(todo._id!)}
                    className="btn btn-sm btn-outline-danger"
                    title="Delete permanently"
                  >
                    Delete
                  </button>
                </div>
              </li>
            ))}
          </ul>
        </div>
      </div>
    </div>
  );
}

export default CompletedTodos;

// FD/angular-todo-app/src/app/completed-todos/completed-todos.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, RouterModule } from '@angular/router';
import { Todo, TodoService, TodoList } from '../todo.service';

@Component({
  selector: 'app-completed-todos',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './completed-todos.component.html',
  styleUrls: ['./completed-todos.component.scss'],
})
export class CompletedTodosComponent implements OnInit {
  completedTodos: Todo[] = [];
  currentListId: string | null = null;
  currentList: TodoList | null = null;

  constructor(
    private todoService: TodoService,
    private route: ActivatedRoute
  ) {}

  ngOnInit(): void {
    this.route.paramMap.subscribe((params) => {
      this.currentListId = params.get('listId');
      if (this.currentListId) {
        this.loadListDetails(this.currentListId);
        this.loadCompletedTodos(this.currentListId);
      }
    });
  }

  loadListDetails(listId: string): void {
    this.todoService.getTodoListById(listId).subscribe(
      (listData) => {
        this.currentList = listData;
      },
      (error) => {
        console.error(`Error list details for ${listId}:`, error);
        this.currentList = null;
      }
    );
  }

  loadCompletedTodos(listId: string): void {
    this.todoService.getTodosForList(listId).subscribe(
      (allTodos) => {
        this.completedTodos = allTodos.filter((todo) => todo.done); // Filter for completed todos
      },
      (error) => {
        console.error(
          `Error loading completed ToDos for list ${listId}:`,
          error
        );
        this.completedTodos = [];
      }
    );
  }

  // This method DELETES a task PERMANENTLY from the completed list
  onDeleteCompletedTodo(todoId: string | undefined): void {
    if (!todoId || !this.currentListId) return;
    if (
      confirm(
        'Are you sure you want to permanently delete this completed task?'
      )
    ) {
      this.todoService.deleteTodoFromList(this.currentListId, todoId).subscribe(
        () => {
          // Backend returns updated list of ALL todos, or just success
          // Reload completed todos
          this.loadCompletedTodos(this.currentListId!);
        },
        (error) => {
          console.error('Error deleting completed todo:', error);
          alert('Failed to delete task. Please try again.');
        }
      );
    }
  }

  // Method to mark a completed task as NOT done (move back to active)
  onMarkAsNotDone(todo: Todo): void {
    if (!this.currentListId || !todo._id) return;
    const updatedTodoData: Todo = { ...todo, done: false };

    this.todoService
      .updateTodoInList(this.currentListId, updatedTodoData)
      .subscribe(
        (savedTodo) => {
          console.log('Todo marked as not done:', savedTodo);
          this.completedTodos = this.completedTodos.filter(
            (t) => t._id !== savedTodo._id
          );
        },
        (error) => {
          console.error('Error marking todo as not done:', error);
          alert('Failed to unmark task. Please try again.');
        }
      );
  }
}

<div class="container mt-4">
  <div class="mb-3">
    <a
      *ngIf="currentListId"
      [routerLink]="['/lists', currentListId]"
      class="btn btn-sm btn-outline-secondary"
    >
      « Back to Active Tasks
    </a>
  </div>

  <div
    *ngIf="currentList"
    class="py-3 px-4 mb-4 bg-light rounded-3 text-center"
  >
    <h1>
      {{ currentList.name }} - Completed Tasks
      <span class="badge bg-success text-white"
        >{{ completedTodos.length }} completed</span
      >
    </h1>
  </div>

  <div id="completed-todo-list" class="row justify-content-center">
    <div class="col-sm-8 col-md-6">
      <ul class="list-group">
        <li
          class="list-group-item d-flex justify-content-between align-items-center"
          *ngFor="let todo of completedTodos"
        >
          <span class="text-decoration-line-through text-muted">
            {{ todo.text }}
          </span>
          <div>
            <button
              (click)="onMarkAsNotDone(todo)"
              class="btn btn-sm btn-outline-warning me-2"
              title="Mark as not done"
            >
              Undo
            </button>
            <button
              (click)="onDeleteCompletedTodo(todo._id)"
              class="btn btn-sm btn-outline-danger"
              title="Delete permanently"
            >
              Delete
            </button>
          </div>
        </li>
      </ul>
      <p
        *ngIf="completedTodos.length === 0 && currentListId"
        class="text-center mt-3"
      >
        No tasks have been completed in this list yet.
      </p>
    </div>
  </div>
</div>
<router-outlet></router-outlet>
