// FD/svelte-todo-app/src/lib/components/TodoListSelector.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { Link } from 'svelte-routing';
  import * as api from '../apiService';
  import type { TodoList } from '../../types';

  let todoLists: TodoList[] = [];
  let newListName: string = '';
  let loading: boolean = true;
  let error: string | null = null;

  onMount(async () => {
    try {
      loading = true;
      error = null;
      todoLists = await api.getTodoLists();
    } catch (err) {
      console.error("Failed to fetch todo lists", err);
      error = "Failed to load lists. Please try again.";
    } finally {
      loading = false;
    }
  });

  async function handleCreateList() {
    if (!newListName.trim()) return;
    try {
      const newList = await api.createTodoList(newListName);
      todoLists = [...todoLists, newList]; // Svelte reactivity: assign to trigger update
      newListName = '';
    } catch (err) {
      console.error("Failed to create todo list", err);
      error = "Failed to create list. Please try again.";
    }
  }

  async function handleDeleteList(listId: string, listName: string) {
    if (window.confirm(`Are you sure you want to delete the list "${listName}" and all its items?`)) {
      try {
        await api.deleteTodoList(listId);
        todoLists = todoLists.filter(list => list._id !== listId);
      } catch (err) {
        console.error(`Failed to delete list ${listId}`, err);
        error = "Failed to delete list. Please try again.";
      }
    }
  }
</script>

<div class="mt-4">
  <h2>Select or Create a ToDo List</h2>

  <form on:submit|preventDefault={handleCreateList} class="mb-4">
    <div class="input-group">
      <input
        type="text"
        class="form-control"
        placeholder="New list name"
        bind:value={newListName}
        required
      />
      <button type="submit" class="btn btn-success">Create List</button>
    </div>
  </form>

  {#if loading}
    <p>Loading lists...</p>
  {:else if error}
    <p style="color: red;">Error: {error}</p>
  {:else if todoLists.length === 0}
    <p class="list-group-item">No ToDo lists found. Create one!</p>
  {:else}
    <div class="list-group">
      {#each todoLists as list (list._id)}
        <div class="list-group-item d-flex justify-content-between align-items-center">
          <Link to={`/lists/${list._id}`} class="flex-grow-1 text-decoration-none text-dark">
            {list.name}
          </Link>
          <button
            type="button"
            class="btn btn-sm btn-outline-danger ms-2"
            on:click={() => handleDeleteList(list._id!, list.name)}
            title="Delete list {list.name}"
          >
            Delete
          </button>
        </div>
      {/each}
    </div>
  {/if}
</div>

// FD/angular-todo-app/src/app/todo-list-selector/todo-list-selector.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router, RouterModule } from '@angular/router';
import { TodoList, TodoService } from '../todo.service';

@Component({
  selector: 'app-todo-list-selector',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterModule],
  templateUrl: './todo-list-selector.component.html',
  styleUrls: ['./todo-list-selector.component.scss'],
})
export class TodoListSelectorComponent implements OnInit {
  todoLists: TodoList[] = [];
  newListName: string = '';

  constructor(private todoService: TodoService, private router: Router) {}

  ngOnInit(): void {
    this.loadTodoLists();
  }

  loadTodoLists(): void {
    this.todoService.getTodoLists().subscribe(
      (data) => {
        this.todoLists = data;
      },
      (error) => {
        console.error('Error loading ToDo lists:', error);
      }
    );
  }

  onCreateList(): void {
    if (!this.newListName.trim()) return;
    this.todoService.createTodoList(this.newListName).subscribe(
      (newList) => {
        this.todoLists.push(newList); // Add to local list
        this.newListName = '';
        // Navigate to the new list:
        this.router.navigate(['/lists', newList._id]);
      },
      (error) => {
        console.error('Error creating ToDo list:', error);
      }
    );
  }

  onDeleteList(listId: string, listName: string, event: MouseEvent): void {
    event.stopPropagation(); // Prevent navigation if the delete button is inside the <a> tag
    event.preventDefault(); // Also prevent default <a> tag behavior

    if (
      confirm(
        `Are you sure you want to delete the list "${listName}" and all its items? This cannot be undone.`
      )
    ) {
      this.todoService.deleteTodoList(listId).subscribe(
        (response) => {
          console.log(response.message); // Log success message from backend
          // Remove the list from the local array to update the UI
          this.todoLists = this.todoLists.filter((list) => list._id !== listId);
        },
        (error) => {
          console.error(`Error deleting ToDo list ${listId}:`, error);
          alert(
            `Failed to delete list: ${error.error?.message || error.message}`
          );
        }
      );
    }
  }
}

<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h2>Select or Create a ToDo List</h2>

      <!-- Form to create new list -->
      <form (ngSubmit)="onCreateList()" class="mb-4">
        <div class="input-group">
          <input
            type="text"
            class="form-control"
            placeholder="New list name"
            [(ngModel)]="newListName"
            name="newListName"
            required
          />
          <button type="submit" class="btn btn-success">Create List</button>
        </div>
      </form>

      <!-- List of existing ToDo lists -->
      <div class="list-group">
        <a
          *ngFor="let list of todoLists"
          [routerLink]="['/lists', list._id]"
          class="list-group-item list-group-item-action d-flex justify-content-between align-items-center"
        >
          <span>{{ list.name }}</span>
          <button
            type="button"
            class="btn btn-sm btn-outline-danger"
            (click)="onDeleteList(list._id, list.name, $event)"
            title="Delete list {{ list.name }}"
          >
            Delete
          </button>
        </a>
        <p *ngIf="todoLists.length === 0" class="list-group-item">
          No ToDo lists found. Create one!
        </p>
      </div>
    </div>
  </div>
</div>
