// FD/angular-todo-app/src/app/todo-detail/todo-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, RouterModule } from '@angular/router';
import { Todo, TodoService, TodoList } from '../todo.service';

@Component({
  selector: 'app-todo-detail',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterModule],
  templateUrl: './todo-detail.component.html',
  styleUrls: ['./todo-detail.component.scss'],
})
export class TodoDetailComponent implements OnInit {
  activeTodos: Todo[] = [];
  newTodoText: string = '';
  currentListId: string | null = null;
  currentList: TodoList | null = null;

  constructor(
    private todoService: TodoService,
    private route: ActivatedRoute
  ) {}

  ngOnInit(): void {
    this.route.paramMap.subscribe((params) => {
      this.currentListId = params.get('listId');
      if (this.currentListId) {
        this.loadListDetails(this.currentListId); // Fetch list name/details
        this.loadActiveTodosForList(this.currentListId); // Fetch only active todos
      }
    });
  }

  loadListDetails(listId: string): void {
    this.todoService.getTodoListById(listId).subscribe(
      (listData) => {
        this.currentList = listData;
      },
      (error) => {
        console.error(`Error loading list details for ${listId}:`, error);
        this.currentList = null;
      }
    );
  }

  // Fetches all todos for the list and then filters for active ones
  loadActiveTodosForList(listId: string): void {
    this.todoService.getTodosForList(listId).subscribe(
      (allTodos) => {
        // Filter for todos that are NOT done
        this.activeTodos = allTodos.filter((todo) => !todo.done);
        console.log('Active todos loaded:', this.activeTodos);
      },
      (error) => {
        console.error(`Error loading ToDos for list ${listId}:`, error);
        this.activeTodos = [];
      }
    );
  }

  onAddTodo(): void {
    if (!this.newTodoText.trim() || !this.currentListId) return;
    this.todoService
      .addTodoToList(this.currentListId, this.newTodoText)
      .subscribe(
        (allTodosAfterAdd) => {
          // Backend returns all todos. We re-filter to update activeTodos.
          this.activeTodos = allTodosAfterAdd.filter((todo) => !todo.done);
          this.newTodoText = '';
        },
        (error) => {
          console.error('Error adding todo:', error);
        }
      );
  }

  // This method now marks a task as done (moves it)
  onMarkAsDone(todo: Todo): void {
    if (!this.currentListId || !todo._id) return;

    const updatedTodoData: Todo = { ...todo, done: true }; // Set done to true

    this.todoService
      .updateTodoInList(this.currentListId, updatedTodoData)
      .subscribe(
        (savedTodo) => {
          console.log('Todo marked as done:', savedTodo);
          // Remove from the local activeTodos list as it's no longer active
          this.activeTodos = this.activeTodos.filter(
            (t) => t._id !== savedTodo._id
          );
        },
        (error) => {
          console.error('Error marking todo as done:', error);
          // Potentially revert UI if an optimistic update was made, or show error
          alert('Failed to mark task as completed. Please try again.');
        }
      );
  }

  // For deleting a task directly from the active list
  onDeleteActiveTodo(todoId: string | undefined): void {
    if (!todoId || !this.currentListId) return;

    // Add a confirmation dialog
    if (confirm('Are you sure you want to permanently delete this task?')) {
      this.todoService.deleteTodoFromList(this.currentListId, todoId).subscribe(
        (allTodosAfterDelete) => {
          // Backend returns all todos. Re-filter for active ones.
          this.activeTodos = allTodosAfterDelete.filter((todo) => !todo.done);
        },
        (error) => {
          console.error('Error deleting active todo:', error);
          alert('Failed to delete task. Please try again.');
        }
      );
    }
  }
}

<div class="container mt-4">
  <div class="mb-3">
    <a routerLink="/lists" class="btn btn-sm btn-outline-secondary"
      >« Back to Lists</a
    >
    <a
      *ngIf="currentListId"
      [routerLink]="['/lists', currentListId, 'completed']"
      class="btn btn-sm btn-info"
    >
      View Completed Tasks
    </a>
  </div>

  <div class="py-3 px-4 mb-4 bg-light rounded-3 text-center">
    <h1>
      {{ currentList?.name || "List " + (currentListId | slice : 0 : 6) }}
      List - ToDo
      <span class="badge bg-primary text-white"
        >{{ activeTodos.length }} left</span
      >
    </h1>
  </div>

  <!-- FORM TO CREATE TODOS -->
  <div id="todo-form" class="row justify-content-center">
    <div class="col-sm-10 col-md-8 text-center">
      <form (ngSubmit)="onAddTodo()">
        <div class="mb-3">
          <input
            type="text"
            class="form-control form-control-lg text-center"
            placeholder="What needs to be done in this list?"
            [(ngModel)]="newTodoText"
            name="newTodoText"
          />
        </div>
        <button type="submit" class="btn btn-primary btn-lg">Add Item</button>
      </form>
    </div>
  </div>

  <!-- ACTIVE TODO LIST -->
  <div id="todo-list" class="row justify-content-center">
    <div class="col-sm-8 col-md-6">
      <div class="list-group">
        <div
          class="list-group-item d-flex justify-content-between align-items-center"
          *ngFor="let todo of activeTodos"
        >
          <div>
            <input
              class="form-check-input me-2"
              type="checkbox"
              (change)="onMarkAsDone(todo)"
              id="todo-{{ todo._id }}"
              [checked]="false"
            />
            <label class="form-check-label" for="todo-{{ todo._id }}">
              {{ todo.text }}
            </label>
          </div>
          <button
            (click)="onDeleteActiveTodo(todo._id)"
            class="btn btn-sm btn-outline-danger"
          >
            Delete
          </button>
        </div>
      </div>
      <p
        *ngIf="activeTodos.length === 0 && currentListId"
        class="text-center mt-3"
      >
        No active tasks in this list. Add some or check completed tasks!
      </p>
    </div>
  </div>
</div>
<router-outlet></router-outlet>

// FD/react-todo-app/src/components/TodoDetail.tsx
import { useState, useEffect } from "react";
import { useParams, Link as RouterLink } from "react-router-dom";
import * as api from "../apiService";
import type { Todo, TodoList } from "../types";

function TodoDetail() {
  const { listId } = useParams<{ listId: string }>();
  const [activeTodos, setActiveTodos] = useState<Todo[]>([]);
  const [currentList, setCurrentList] = useState<TodoList | null>(null);
  const [newTodoText, setNewTodoText] = useState("");
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!listId) return;

    const fetchListDetailsAndTodos = async () => {
      try {
        setLoading(true);
        setError(null);
        // Fetch list details (for name)
        const listDetails = await api.getTodoListById(listId);
        setCurrentList(listDetails);

        // Fetch todos and filter for active
        const allTodos = await api.getTodosForList(listId);
        setActiveTodos(allTodos.filter((todo) => !todo.done));
      } catch (err) {
        console.error("Failed to load list details or todos", err);
        setError("Failed to load data for this list.");
      } finally {
        setLoading(false);
      }
    };

    fetchListDetailsAndTodos();
  }, [listId]); // Re-run if listId changes

  const handleAddTodo = async (event: React.FormEvent) => {
    event.preventDefault();
    if (!newTodoText.trim() || !listId) return;
    try {
      const allTodosAfterAdd = await api.addTodoToList(listId, newTodoText);
      setActiveTodos(allTodosAfterAdd.filter((todo) => !todo.done));
      setNewTodoText("");
    } catch (err) {
      console.error("Failed to add todo", err);
      setError("Failed to add item. Please try again.");
    }
  };

  const handleMarkAsDone = async (todo: Todo) => {
    if (!listId || !todo._id) return;
    try {
      await api.updateTodoInList(listId, todo._id, { done: true });
      setActiveTodos((prevTodos) =>
        prevTodos.filter((t) => t._id !== todo._id)
      );
    } catch (err) {
      console.error("Failed to mark as done", err);
      setError("Failed to update item. Please try again.");
    }
  };

  const handleDeleteActiveTodo = async (todoId: string) => {
    if (!listId) return;
    if (
      window.confirm("Are you sure you want to permanently delete this task?")
    ) {
      try {
        const allTodosAfterDelete = await api.deleteTodoFromList(
          listId,
          todoId
        );
        setActiveTodos(allTodosAfterDelete.filter((todo) => !todo.done));
      } catch (err) {
        console.error("Failed to delete active todo", err);
        setError("Failed to delete item. Please try again.");
      }
    }
  };

  if (loading)
    return (
      <div className="container mt-4">
        <p>Loading todo items...</p>
      </div>
    );
  if (error)
    return (
      <div className="container mt-4">
        <p style={{ color: "red" }}>Error: {error}</p>
      </div>
    );
  if (!currentList)
    return (
      <div className="container mt-4">
        <p>List not found.</p>
      </div>
    );

  return (
    <div className="container mt-4">
      <div className="d-flex justify-content-between align-items-center mb-3">
        <RouterLink to="/lists" className="btn btn-sm btn-outline-secondary">
          « Back to Lists
        </RouterLink>
        <RouterLink
          to={`/lists/${listId}/completed`}
          className="btn btn-sm btn-info"
        >
          View Completed Tasks
        </RouterLink>
      </div>

      <div className="py-3 px-4 mb-4 bg-light rounded-3 text-center">
        <h1>
          {currentList.name} - Active Tasks
          <span className="badge bg-primary text-white ms-2">
            {activeTodos.length}
          </span>
        </h1>
      </div>

      <form
        onSubmit={handleAddTodo}
        className="row justify-content-center mb-4"
      >
        <div className="col-sm-10 col-md-8 text-center">
          <div className="input-group">
            <input
              type="text"
              className="form-control form-control-lg text-center"
              placeholder="What needs to be done?"
              value={newTodoText}
              onChange={(e) => setNewTodoText(e.target.value)}
              name="newTodoText"
            />
            <button type="submit" className="btn btn-primary btn-lg">
              Add Item
            </button>
          </div>
        </div>
      </form>

      <div className="row justify-content-center">
        <div className="col-sm-8 col-md-6">
          <div className="list-group">
            {activeTodos.length === 0 && (
              <p className="list-group-item text-center">No active tasks!</p>
            )}
            {activeTodos.map((todo) => (
              <div
                key={todo._id}
                className="list-group-item d-flex justify-content-between align-items-center"
              >
                <div>
                  <input
                    className="form-check-input me-2"
                    type="checkbox"
                    onChange={() => handleMarkAsDone(todo)}
                    id={`todo-${todo._id}`}
                    checked={false}
                  />
                  <label
                    className="form-check-label"
                    htmlFor={`todo-${todo._id}`}
                  >
                    {todo.text}
                  </label>
                </div>
                <button
                  onClick={() => handleDeleteActiveTodo(todo._id!)}
                  className="btn btn-sm btn-outline-danger"
                >
                  Delete
                </button>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}

export default TodoDetail;
